#    __ ___ __  __
#   / //_(_) /_/ /___ __
#  / ,< / / __/ __/ // /
# /_/|_/_/\__/\__/\_, /
#                /___/
#
# Configuration

font_family FiraCode Nerd Font
bold_font FiraCode Nerd Font Bold
italic_font FiraCode Nerd Font Italic
bold_italic_font FiraCode Nerd Font Bold Italic
font_size                   12
remember_window_size        no
initial_window_width        950
initial_window_height       500
cursor_blink_interval       0.5
cursor_stop_blinking_after  1
scrollback_lines            2000
wheel_scroll_min_lines      1
enable_audio_bell           no
window_padding_width        10
hide_window_decorations     no
background_opacity          0.5
dynamic_background_opacity  yes
confirm_os_window_close     0
selection_foreground        none
selection_background        none
allow_remote_control yes

#Include matugen theme
#include ~/.config/kitty/themes/colors-matugen.conf

# Include Custom Configuration
# Create the file custom.conf in ~/.config/kitty to overwrite the default configuration
#include ./custom.conf

# ─────────────────────────────
# 🎨 Tab Bar Styling (Matugen Look)
# ─────────────────────────────

tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style angled
tab_title_template " {index}: {title} "
tab_separator " "

# Colors
active_tab_foreground   #ffffff
active_tab_background   #cba6f7   
inactive_tab_foreground #bda8d6   
inactive_tab_background #1b0835   

# Optional: make the tab bar subtly glow at the bottom
tab_bar_background #1a0830
# Hide bar when only one tab is open (optional)
# hide_tab_bar_if_only_one_tab yes
clipboard_control write-clipboard write-primary no-append read-clipboard read-primary
