# Optional preload (not strictly needed)
# preload = /home/bogdan/wallpapers/anime1.png

# Wallpaper for your laptop monitor
wallpaper {
    monitor = eDP-1
    path = /home/bogdan/wallpapers/anime1.png
    fit_mode = cover
}

# Optional misc options
splash = false
ipc = true
